export const shebangMap: Record<string, string> = {
  node: "Javascript",
  jsc: "Javascript",
  rhino: "Javascript",
  deno: "Typescript",
  bun: "Javascript",
  python3: "Python",
  python2: "Python",
  python: "Python",
  php: "PHP",
  perl: "Perl",
  ruby: "Ruby",
  bash: "Bash",
  sh: "Bash",
  zsh: "Bash",
  lua: "Lua",
  julia: "Julia",
  kotlin: "Kotlin",
  racket: "Racket",
  sbcl: "Common Lisp",
  guile: "Scheme",
  csi: "Scheme",
  fish: "Fish",
  elixir: "Elixir",
  nix: "Nix",
  awk: "Awk",
  sed: "Sed",
  tcl: "Tcl",
  groovy: "Groovy",
  scala: "Scala",
  dart: "Dart",
  swift: "Swift",
};
